### ISSUE TITLE
Module does not work on windows

### ISSUE THREAD

**Issue by nils-a** [cake-contrib/Cake.Npm.Module#9]
Using the module under windows results in the following error:

```
❯ .\build.ps1 --verbosity=diagnostic
Preparing to run build script...
Running build script...
Registering module Cake.Npm.Module.NpmModule...
Analyzing build script...
Analyzing D:/_dev/Cake.Npm.Module.Tests2/build.cake...
Processing build script...
Installing addins...
Installing package asciidoctor with npm...
Executing: "npm" install --verbose asciidoctor
Error: System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Cake.Core.IO.ProcessRunner.Start(FilePath filePath, ProcessSettings settings)
   at Cake.Npm.Module.NpmPackageInstaller.Install(PackageReference package, PackageType type, DirectoryPath path)
   at Cake.Core.Scripting.ScriptProcessor.InstallAddins(ScriptAnalyzerResult analyzerResult, DirectoryPath installPath)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
   at Cake.Commands.BuildCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(CakeOptions options)
   at Cake.Program.Main()

```

**Comment by nils-a** [comment]
I'm guessing the source for the errror is https://github.com/cake-contrib/Cake.Npm.Module/blob/develop/src/Cake.Npm.Module/NpmPackageInstaller.cs#L96 : On windows it should probably be something like "npm.cmd"

**Comment by gep13** [comment]
@nils-a if npm is installed globally, the `npm` command should indeed work on Windows.

**Comment by nils-a** [comment]
@gep13 interesting.. It is gobally installed:

```
❯ choco search npm -lo
Chocolatey v0.10.15
nodejs 14.10.1
nodejs.install 14.10.1
2 packages installed.

❯ $env:Path.split(";") | ? { $_ -like "*node*" }
C:\Program Files\nodejs\

❯ which npm
C:\Program Files\nodejs\npm.cmd

❯ npm --version
6.14.8
```

Additionally, the error mentioned above goes away, if I replace `"npm"` with `"npm.cmd"` in https://github.com/cake-contrib/Cake.Npm.Module/blob/develop/src/Cake.Npm.Module/NpmPackageInstaller.cs#L96. 

I'll dig deeper into this.

**Comment by nils-a** [comment]
@gep13 I think you may be wrong here :-)

I did a simple test: create some bat-file (or cmd, doesn't matter) and place it in the path.
calling it with the extension works normally using `Process.Start()` while calling it without extension only works when setting `UseShellExecute = true` at the same time.

**Comment by gep13** [comment]
>@nils-a said...
I think you may be wrong here :-)

It wouldn't be the first time 😄 

Thanks for digging into this and for providing a PR!
